Repository derisk-ai/OpenDerisk, pull requests merged in 2025-09, with the labels that each got.

#61 feat: mcp
  web/src/app/mcp/detail/index.css
  web/src/app/mcp/detail/page.tsx
  web/src/app/mcp/page.tsx
  web/src/contexts/chat-content-context.tsx
Labels: enhancement

#63 feat: add new vis components config file
  web/README.md
  web/src/components/chat/chat-content-components/VisComponents/RefsCard/index.tsx
  web/src/components/chat/chat-content-components/VisComponents/config.tsx
  web/src/components/chat/chat-content-components/config.tsx
Labels: enhancement

#64 docs: add Japanese README
  README.ja.md
  README.md
  README.zh.md
Labels: documentation

#65 docs: add deepwiki for OpenDerisk v0.2
  README.ja.md
  README.md
  README.zh.md
Labels: documentation

#68 fix:batch process embeddings while call OpenAI embedding API
  packages/derisk-core/src/derisk/rag/embedding/embeddings.py
Labels: fix

#70 feat: add-knowledge-chunk
  web/src/app/knowledge/chunk/page.tsx
  web/src/components/knowledge/doc-panel.tsx
  web/src/components/knowledge/menu-modal.tsx
Labels: enhancement

#71 feat: add mcp server registry and call features
  README.md
  README.zh.md
  packages/derisk-core/src/derisk/agent/resource/tool/mcp/mcp_utils.py
  web/src/app/mcp/CreatMcpModel.tsx
  web/src/app/mcp/detail/index.css
  web/src/app/mcp/detail/page.tsx
  web/src/app/mcp/page.tsx
  web/src/client/api/request.ts
  web/src/locales/en/common.ts
  web/src/locales/zh/common.ts
Labels: enhancement

#76 fix:reasoning agent find knowledge empty.
  packages/derisk-serve/src/derisk_serve/agent/resource/knowledge_pack.py
  packages/derisk-serve/src/derisk_serve/rag/operators/knowledge_space.py
  packages/derisk-serve/src/derisk_serve/rag/service/service.py
Labels: fix

#78 feat: add mcp
  web/src/app/application/structure/components/base-config/index.tsx
  web/src/app/application/structure/components/base-config/tools-modal.tsx
  web/src/components/chat/content/chat-content.tsx
Labels: enhancement
